device-management-toolkit/sample-web-ui

- package-lock.json
- package.json
> build(deps): update mps-ui-toolkit to ui-toolkit

- package-lock.json
- src/components/app/app.js
- src/components/pages/index.js
- src/components/pages/networkconfigs/networkconfigs.container.js
- src/components/pages/networkconfigs/networkconfigs.js
- src/components/pages/networkconfigs/networkconfigs.test.js
> feat: network configs

- .github/workflows/docker-image-ci.yml
- .github/workflows/docker-image.yml
> ci: add docker ci

- Dockerfile
- init.sh
> refactor(docker): optimize how server is set

- package-lock.json
- package.json
- src/components/pages/dashboard/dashboard.container.js
- src/components/pages/devices/devices.container.js
- src/components/pages/landing/landing.container.js
- src/components/pages/login/login.container.js
- src/components/shared/protected/protected.container.js
> build(deps): remove recompose

- cypress/README.md
- cypress/integration/cira.spec.js
fix: removed an issue in cira test
> docs: added documentation for Cypress

- src/app/configs/config-detail/config-detail.component.html
> refactor(cira-configs): update text for cira config creation

- src/app/dashboard/dashboard.component.html
- src/app/dashboard/dashboard.component.scss
- src/app/dashboard/dashboard.component.ts
closes [AB#2329](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/2329)
> refactor(dashboard): update dashboard design

- init.sh
- src/app/auth.service.ts
- src/app/devices/device-toolbar/device-toolbar.component.html
- src/app/devices/device-toolbar/device-toolbar.component.ts
- src/app/devices/devices.component.ts
- src/app/shared/add-device/add-device.component.html
- src/app/shared/add-device/add-device.component.ts
- src/app/shared/deactivate-device/deactivate-device.component.html
- src/app/shared/deactivate-device/deactivate-device.component.spec.ts
- src/app/shared/deactivate-device/deactivate-device.component.ts
- src/app/shared/deactivate-device/vault.service.spec.ts
- src/app/shared/deactivate-device/vault.service.ts
- src/app/shared/shared.module.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
[AB#2321](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/2321)
> feat(device-details): add RPC deactivation command generation dialog

- src/app/devices/device-detail/device-detail.component.ts
> refactor(device-detail): api calls are fully async

- package-lock.json
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/auth.service.ts
- src/app/core/navbar/navbar.component.html
- src/app/profiles/profile-detail/profile-detail.component.html
- src/app/profiles/profile-detail/profile-detail.component.scss
- src/app/profiles/profile-detail/profile-detail.component.spec.ts
- src/app/profiles/profile-detail/profile-detail.component.ts
- src/app/shared/config/Constants.ts
- src/app/shared/shared.module.ts
- src/app/wireless/wireless-detail/wireless-detail.component.html
- src/app/wireless/wireless-detail/wireless-detail.component.spec.ts
- src/app/wireless/wireless-detail/wireless-detail.component.ts
- src/app/wireless/wireless.component.html
- src/app/wireless/wireless.component.spec.ts
- src/app/wireless/wireless.component.ts
- src/app/wireless/wireless.service.spec.ts
- src/app/wireless/wireless.service.ts
- src/models/models.ts
- tsconfig.json
Closes [AB#2756](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/2756)
> feat(wireless): add wireless config control

- src/app/profiles/profile-detail/profile-detail.component.html
- src/app/profiles/profile-detail/profile-detail.component.scss
- src/app/profiles/profile-detail/profile-detail.component.ts
Closes [AB#2950](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/2950), [AB#2953](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/2953)
> fix(wireless): fix delete button alignment and empty search result ui

- src/app/profiles/profile-detail/profile-detail.component.html
- src/app/profiles/profile-detail/profile-detail.component.scss
- src/app/profiles/profile-detail/profile-detail.component.spec.ts
- src/app/profiles/profile-detail/profile-detail.component.ts
- src/app/shared/config/Constants.ts
> fix(profile): fix no wifi config found message on input focus

- src/app/dashboard/dashboard.component.html
- src/app/dashboard/dashboard.component.scss
Closes [AB#3473](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/3473)
> feat(dashboard): add wireless config link to dashboard page

- cypress/fixtures/apiResponses.json
- cypress/fixtures/eventlogs.json
- cypress/integration/eventlog/get.spec.js
- package-lock.json
- package.json
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/devices/device-detail/device-detail.component.html
- src/app/devices/devices.service.ts
- src/app/devices/event-log/event-log.component.html
- src/app/devices/event-log/event-log.component.spec.ts
- src/app/devices/event-log/event-log.component.ts
- src/app/shared/config/Constants.ts
- src/models/models.ts
Closes [AB#3610](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/3610), [AB#3611](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/3611), [AB#3614](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/3614)
> feat(eventlog): add event log UI

- .github/workflows/nodejs.yaml
> ci(nodejs): replace node v15 with node v16

- package-lock.json
- package.json
> build(version): bump to v2.1.0

- Jenkinsfile
> ci: Scan only main

- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/auth.service.spec.ts
- src/app/auth.service.ts
- src/app/configs/configs.component.ts
- src/app/configs/configs.service.ts
- src/app/devices/kvm/kvm.component.ts
- src/app/domains/domain-detail/domain-detail.component.spec.ts
- src/app/event-channel/event-channel.component.spec.ts
- src/app/event-channel/event-channel.service.spec.ts
- src/app/shared/config/Constants.ts
- src/app/wireless/wireless.component.ts
- src/app/wireless/wireless.service.ts
> test(auth): increased code coverage for auth.service.ts

- cypress/fixtures/api/apiResponses.ts
- cypress/fixtures/profile.ts
- cypress/integration/profile/create-error.spec.ts
- cypress/integration/profile/create.spec.ts
- cypress/integration/profile/delete.spec.ts
- cypress/support/index.d.ts
- cypress/support/index.ts
- src/environments/environment.ts
> test(e2e): fix tls profile creation

- src/app/domains/domain-detail/domain-detail.component.spec.ts
- src/app/domains/domains.service.spec.ts
> test(domains): increased code coverage for domains

- package-lock.json
- src/app/profiles/profiles.service.spec.ts
> test(profile): increased code coverage for profile.service.ts

- debug.log
- src/app/devices/device-toolbar/device-toolbar.component.spec.ts
- src/app/devices/device-user-consent/device-user-consent.component.spec.ts
- src/app/devices/devices.component.spec.ts
- src/app/devices/devices.component.ts
- src/app/devices/devices.service.spec.ts
- src/app/devices/devices.service.ts
- src/app/shared/random-pass-alert/random-pass-alert.component.spec.ts
> test(devices): increased code coverage for devices

- cypress/fixtures/api/apiResponses.ts
- cypress/integration/cira/create-error.spec.ts
- cypress/integration/cira/create.spec.ts
- cypress/integration/cira/delete.spec.ts
- cypress/integration/device/device-details.spec.ts
- cypress/integration/device/device.spec.ts
- cypress/integration/device/paging.spec.ts
- cypress/integration/domain/create.spec.ts
- cypress/integration/domain/delete.spec.ts
- cypress/integration/eventlog/get.spec.ts
- cypress/integration/login/login.spec.ts
- cypress/integration/login/test.spec.ts
- cypress/integration/profile/create-error.spec.ts
- cypress/integration/profile/create-tls.spec.ts
- cypress/integration/profile/create.spec.ts
- cypress/integration/profile/delete-tls.spec.ts
- cypress/integration/profile/delete.spec.ts
- cypress/integration/wireless/create-error.spec.ts
- cypress/integration/wireless/create.spec.ts
- cypress/integration/wireless/delete.spec.ts
- cypress/support/index.ts
> refactor(cypress): consolidate http codes

- package-lock.json
- src/app/shared/add-device/add-device.component.spec.ts
- src/app/shared/add-device/add-device.component.ts
> refactor(add-dialog): uses rpc-go syntax

- .github/workflows/cypress.yaml
> ci(cypress): set to run node 16 only

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/devices/kvm/kvm.component.ts
- src/app/devices/sol/sol.component.ts
- src/models/models.ts
> build(deps): update @open-amt-cloud-toolkit to v2.0.5

- cypress/integration/cira/create.spec.ts
> refactor: fix status code expectation

- cypress/integration/cira/create.spec.ts
- cypress/integration/device/device-details.spec.ts
- src/app/devices/device-detail/device-detail.component.html
> test(devices): Adds Cypress attributes to HTML and adds Device Details test

- cypress/fixtures/api/apiResponses.ts
- cypress/fixtures/profile.ts
- cypress/integration/profile/create-static-cira.spec.ts
- cypress/integration/profile/delete-static-cira.spec.ts
- src/app/profiles/profile-detail/profile-detail.component.html
- src/app/profiles/profile-detail/profile-detail.component.spec.ts
- src/app/profiles/profile-detail/profile-detail.component.ts
- src/app/shared/shared.module.ts
- src/app/shared/static-cira-warning/static-cira-warning.component.html
- src/app/shared/static-cira-warning/static-cira-warning.component.spec.ts
- src/app/shared/static-cira-warning/static-cira-warning.component.ts
- Removed mutually exclusive condition on CIRA configuration and static IP network configuration
- Added AMT version warning message when creating a profile using CIRA and a static IP network configuration simultaneously
- Added UI unit testing
[#591](https://github.com/open-amt-cloud-toolkit/rps/pull/591)
> feat: cira + static ip configuration warning

- cypress/fixtures/api/apiResponses.ts
- cypress/integration/device/device-details.spec.ts
- src/app/devices/device-detail/device-detail.component.html
> test(device): Remove flakey tests

- cypress/fixtures/profile.ts
- cypress/integration/profile/create-static-cira.spec.ts
- cypress/integration/profile/delete-static-cira.spec.ts
- cypress/support/index.ts
- src/app/profiles/profiles.component.html
> test(static): Fix CIRA with Static Cypress tests

- src/app/devices/kvm/kvm.component.spec.ts
- src/app/devices/kvm/kvm.component.ts
- src/app/devices/sol/sol.component.spec.ts
- src/app/devices/sol/sol.component.ts
> fix(redirection): adds property to track redirection state

- cypress.json
- cypress/fixtures/api/apiResponses.ts
- cypress/fixtures/profile.ts
- cypress/integration/profile/create-tls.spec.ts
- cypress/integration/profile/update.spec.ts
- cypress/support/index.ts
> test(profile): automated update workflows

- CHANGELOG.md
- package-lock.json
- package.json
> build(version): bump to v2.3.0

- cypress.json
- cypress/integration/domain/vault-read-certificate.spec.ts
> test(domain): automated vault read certificate and password

- cypress.json
- src/app/devices/device-detail/device-detail.component.html
- src/app/devices/sol/sol.component.spec.ts
- src/app/login/login.component.spec.ts
- src/app/login/login.component.ts
- src/app/shared/static-cira-warning/static-cira-warning.component.spec.ts
> test(cira): fixes errors regarding unknown elements

- cypress/integration/device/device-details.spec.ts
- src/app/devices/device-detail/device-detail.component.html
- src/app/devices/device-detail/device-detail.component.spec.ts
- src/app/devices/device-detail/device-detail.component.ts
- src/app/devices/device-toolbar/device-toolbar.component.html
> feat(devices): differentiation between out-of-band and in-band power actions

- cypress/e2e/integration/wireless/create-error.spec.ts
- cypress/e2e/integration/wireless/create.spec.ts
- cypress/support/commands.ts
> test(wireless): remove hardcoded values

- cypress.config.ts
- cypress/e2e/integration/device/device-details.spec.ts
- cypress/e2e/integration/rpc/activateAmtDevice.spec.ts
- cypress/e2e/integration/rpc/deactivateAmtDevice.spec.ts
- cypress/e2e/integration/rpc/infoAmtDevice.spec.ts
- package-lock.json
- package.json
> test(e2e): update cypress tests to be cross platform compatible

- cypress/e2e/fixtures/profile.ts
- cypress/e2e/integration/profile/create-error.spec.ts
- cypress/e2e/integration/profile/create-static-cira.spec.ts
- cypress/e2e/integration/profile/create-tls.spec.ts
- cypress/e2e/integration/profile/create.spec.ts
- cypress/support/commands.ts
- src/app/profiles/profile-detail/profile-detail.component.html
- src/app/profiles/profile-detail/profile-detail.component.spec.ts
- src/app/profiles/profile-detail/profile-detail.component.ts
- src/app/shared/config/Constants.ts
> feat(profile): add user consent, ider, kvm, sol options - 7399

- cypress/support/commands.ts
- src/app/profiles/profile-detail/profile-detail.component.html
> refactor(profile): hide amt features until fully implemented

- src/app/devices/device-detail/device-detail.component.html
- src/app/devices/device-detail/device-detail.component.scss
- src/app/devices/device-toolbar/device-toolbar.component.html
> revert: put power menu options back on device-toolbar

- src/app/configs/config-detail/config-detail.component.html
- src/app/configs/config-detail/config-detail.component.spec.ts
- src/app/configs/config-detail/config-detail.component.ts
> fix(cira): remove auto-load slider, always auto-load certificate

- CHANGELOG.md
- package-lock.json
- package.json
> chore: update changelog and package.json for v2.4.0

- Dockerfile
> fix(build): build now uses production config for docker

- src/app/dashboard/dashboard.component.scss
> fix: icons now display correctly on dashboard

- cypress/support/commands.ts
- src/app/profiles/profile-detail/profile-detail.component.html
> feat(amtprofilefeatures): re-enable profile features

- src/app/devices/device-user-consent/device-user-consent.component.html
- src/app/devices/kvm/kvm.component.spec.ts
- src/app/devices/kvm/kvm.component.ts
- src/app/devices/sol/sol.component.spec.ts
- src/app/devices/sol/sol.component.ts
> fix(kvm): user consent code on enter was sending cancel

- CHANGELOG.md
- package-lock.json
- package.json
> docs: updates changelog for v2.5.0

- cypress/e2e/fixtures/api/cira.ts
- cypress/e2e/integration/cira/inUseDelete.spec.ts
- src/app/configs/configs.component.html
- src/app/profiles/profiles.component.html
- src/app/shared/are-you-sure/are-you-sure.component.html
> test(ciraconfig): added test to delete an in use config

- .github/workflows/projectsSync.yaml
> ci: add project sync to sample-web-ui

- .github/commitlint.config.js
> ci: add scope for e2e

- .github/commitlint.config.js
- cypress/e2e/integration/rpc/activation.spec.ts
- package-lock.json
- package.json
> test(e2e): update cypress and change device tests

- CHANGELOG.md
- package-lock.json
- package.json
> build: update version to v2.5.1, update changelog

- CHANGELOG.md
- package.json
> build: update version to v2.6.0, update changelog

- CHANGELOG.md
- package-lock.json
- package.json
> build: update package.json and changelog to v2.7.0

- .github/workflows/nodejs.yaml
> ci(deps): bump codecov to 3.1.3

- package-lock.json
- package.json
> build(deps-dev): Bump @angular/cli from 15.2.6 to 15.2.7

- CHANGELOG.md
- package-lock.json
- package.json
> build: update package.json and changelog to v2.8.0

- CHANGELOG.md
- package-lock.json
- package.json
> build: update version and changelog to v2.9.0

- src/app/configs/config-detail/config-detail.component.ts
- src/app/configs/configs.component.spec.ts
- src/app/configs/configs.component.ts
- src/app/configs/configs.service.ts
- src/app/domains/domains.service.ts
- src/app/ieee8021x/ieee8021x.service.ts
- src/app/profiles/profile-detail/profile-detail.component.ts
- src/app/profiles/profiles.component.spec.ts
- src/app/profiles/profiles.component.ts
- src/app/profiles/profiles.service.ts
- src/app/wireless/wireless.service.ts
> fix: url encode get and delete REST path params

- CHANGELOG.md
- package-lock.json
- package.json
> build: update version and changelog to v2.9.1

- .github/workflows/nodejs.yaml
> ci: remove node14 and add node 20

- Dockerfile
- docker-compose.yml
- init.sh
> build(docker): set base image to nginx:bullseye

- .github/workflows/release.yml
- .releaserc.json
> build: automated versioning and publishing

- src/app/ieee8021x/ieee8021x.constants.ts
> feat: add MSCHAPv2 for wired and wireless

- package-lock.json
- package.json
> build(deps-dev): bump @angular/cli to 16.1.3

- CHANGELOG.md
- package-lock.json
- package.json
> feat: upgraded to angular 16

- cypress/support/commands.ts
> fix: profile creation issue

- docker-compose.yml
> build(docker): unpin docker compose minor revision

- Dockerfile
Reverts open-amt-cloud-toolkit/sample-web-ui#1254
> revert(deps): Bump node from 18 to 20

- src/app/app.component.html
- src/styles/open-amt-theme.scss
> refactor: fix dark theme

- package-lock.json
- package.json
> build: bump @angular/cli to "16.1.8"

- .releaserc.json
> ci: updated semantic release

- cypress/e2e/integration/rpc/activation.spec.ts
> fix: updates status message test

- src/app/auth.service.spec.ts
- src/app/configs/config-detail/config-detail.component.spec.ts
- src/app/devices/device-detail/device-detail.component.spec.ts
- src/app/devices/devices.service.spec.ts
- src/app/domains/domains.service.spec.ts
- src/app/ieee8021x/ieee8021x.service.spec.ts
- src/app/login/login.component.spec.ts
- src/app/login/login.component.ts
- src/app/profiles/profiles.service.spec.ts
- src/app/wireless/wireless.service.spec.ts
> test: ensure async, subscribe and fakeAsync are used properly

- .releaserc.json
> ci: update the semantic release plugins

- CHANGELOG.md
- package-lock.json
- package.json
> build: update package.json and changelog

- src/app/app.module.ts
- src/app/devices/device-toolbar/device-toolbar.component.html
- src/app/devices/device-toolbar/device-toolbar.component.scss
- src/app/devices/devices.component.html
- src/app/devices/devices.component.scss
- src/app/devices/devices.component.spec.ts
- src/app/devices/devices.component.ts
- src/app/devices/devices.service.spec.ts
- src/app/devices/devices.service.ts
- src/app/devices/edit-tags/edit-tags.component.html
- src/app/devices/edit-tags/edit-tags.component.spec.ts
- src/app/devices/edit-tags/edit-tags.component.ts
- src/app/profiles/profile-detail/profile-detail.component.spec.ts
- src/app/profiles/profile-detail/profile-detail.component.ts
- src/utils.ts
edit tags for a single device
bulk edit common tags across selected devices
added sorting for tag lists
> feat: edit device tags

- .github/workflows/cypress.yaml
- .github/workflows/release.yml
- Dockerfile
> ci: update to node 20

- .github/workflows/release.yml
> ci: add `persist-credentials:false` to checkout

- .releaserc.json
> fix: update ci automation to correct tag to webui

- cypress/support/commands.ts
- src/app/core/about/about.component.html
- src/app/core/about/about.component.scss
- src/app/core/about/about.component.spec.ts
- src/app/core/about/about.component.ts
- src/app/devices/devices.component.spec.ts
- src/app/login/login.component.spec.ts
- src/app/login/login.component.ts
> feat: about notice appears after login

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/devices/device-toolbar/device-toolbar.component.ts
- src/app/devices/devices.service.spec.ts
- src/app/devices/devices.service.ts
- src/app/devices/kvm/kvm.component.html
- src/app/devices/kvm/kvm.component.spec.ts
- src/app/devices/kvm/kvm.component.ts
- src/models/models.ts
> feat: enable IDER functionality

- .github/workflows/trivy-scan.yaml
> ci: add trivy results to github security tab

- CHANGELOG.md
- package-lock.json
- package.json
> fix: package version and changelog

- CHANGELOG.md
- package-lock.json
- package.json
> fix: update build tasks

- CHANGELOG.md
> chore: update build tasks, package.json and changelog

- .github/workflows/trivy-scan.yaml
> ci: address permissions for trivy-scan to upload

- package-lock.json
- package.json
> build: removed deprecated @angular/flex-layout

- package-lock.json
- package.json
- src/app/devices/sol/sol.component.scss
> chore: updated dependencies

- src/app/core/about/about.component.html
- src/app/core/about/about.component.ts
- src/app/core/toolbar/toolbar.component.html
- src/app/login/login.component.ts
> refactor: remove "Sample UI" and popup for console

- src/app/app.component.html
- src/app/configs/config-detail/config-detail.component.html
- src/app/configs/configs.component.html
- src/app/core/toolbar/toolbar.component.html
- src/app/dashboard/dashboard.component.html
- src/app/devices/audit-log/audit-log.component.html
- src/app/devices/device-detail/device-detail.component.html
- src/app/devices/device-toolbar/device-toolbar.component.html
- src/app/devices/devices.component.html
- src/app/devices/edit-tags/edit-tags.component.html
- src/app/devices/event-log/event-log.component.html
- src/app/devices/kvm/kvm.component.html
- src/app/devices/sol/sol.component.html
- src/app/domains/domain-detail/domain-detail.component.html
- src/app/domains/domains.component.html
- src/app/ieee8021x/ieee8021x-detail/ieee8021x-detail.component.html
- src/app/ieee8021x/ieee8021x.component.html
- src/app/login/login.component.html
- src/app/profiles/profile-detail/profile-detail.component.html
- src/app/profiles/profiles.component.html
- src/app/shared/add-device-enterprise/add-device-enterprise.component.html
- src/app/shared/add-device/add-device.component.html
- src/app/wireless/wireless-detail/wireless-detail.component.html
- src/app/wireless/wireless.component.html
> refactor: use control flow syntax

- src/app/app-routing.module.ts
- src/app/devices/devices.component.html
- src/app/devices/devices.component.ts
> feat: adds amt explorer

- src/app/devices/audit-log/audit-log.component.html
- src/app/devices/audit-log/audit-log.component.scss
- src/app/devices/audit-log/audit-log.component.ts
> feat: adds audit log exstr data to table

- .github/workflows/semantic.yml
> ci: update toplevel permissions for semantic.yml

- src/app/devices/event-log/event-log.component.html
- src/app/devices/event-log/event-log.component.ts
> fix: updates event log to show decoded event information

- src/app/profiles/profile-detail/profile-detail.component.html
- src/app/profiles/profile-detail/profile-detail.component.ts
> feat: allow nontls option for console

- .github/workflows/trivy-scan.yaml
> ci: update permissions from workflow to job

- src/app/devices/audit-log/audit-log.component.html
- src/app/devices/audit-log/audit-log.component.spec.ts
- src/app/devices/audit-log/audit-log.component.ts
> fix: update audit log paging to use paginator correctly

- CHANGELOG.md
- src/app/auth.service.ts
- src/app/configs/configs.component.ts
- src/app/configs/configs.constants.ts
- src/app/configs/configs.service.ts
- src/app/core/toolbar/toolbar.component.ts
- src/app/devices/devices.service.ts
- src/app/devices/general/general.component.ts
- src/app/devices/kvm/kvm.component.ts
- src/app/devices/sol/sol.component.ts
- src/app/profiles/profile-detail/profile-detail.component.ts
- src/models/models.ts
> refactor: rename and remove unused types

- src/app/configs/config-detail/config-detail.component.ts
- src/app/devices/alarms/alarms.component.ts
- src/app/devices/devices.component.ts
- src/app/devices/devices.service.ts
- src/app/devices/general/general.component.ts
- src/app/domains/domain-detail/domain-detail.component.ts
- src/app/domains/domains.component.spec.ts
- src/app/domains/domains.component.ts
- src/app/domains/domains.service.ts
- src/models/models.ts
> refactor: remove deprecated subscribe calls

- src/app/devices/audit-log/audit-log.component.spec.ts
- src/app/devices/device-user-consent/device-user-consent.component.ts
- src/app/devices/devices.service.ts
- src/app/devices/kvm/kvm.component.spec.ts
- src/app/devices/kvm/kvm.component.ts
- src/app/devices/sol/sol.component.spec.ts
- src/app/devices/sol/sol.component.ts
- src/app/ieee8021x/ieee8021x-detail/ieee8021x-detail.component.spec.ts
- src/app/ieee8021x/ieee8021x-detail/ieee8021x-detail.component.ts
- src/app/ieee8021x/ieee8021x.component.ts
- src/app/ieee8021x/ieee8021x.constants.ts
- src/app/ieee8021x/ieee8021x.service.spec.ts
- src/app/ieee8021x/ieee8021x.service.ts
- src/app/profiles/profile-detail/profile-detail.component.spec.ts
- src/app/profiles/profile-detail/profile-detail.component.ts
- src/app/wireless/wireless-detail/wireless-detail.component.ts
- src/app/wireless/wireless.component.ts
- src/app/wireless/wireless.constants.ts
- src/app/wireless/wireless.service.spec.ts
- src/app/wireless/wireless.service.ts
- src/models/models.ts
> refactor: consolidates types, consistent naming convention

- src/app/devices/device-toolbar/device-toolbar.component.html
- src/app/devices/device-toolbar/device-toolbar.component.spec.ts
- src/app/devices/device-toolbar/device-toolbar.component.ts
- src/app/devices/kvm/kvm.component.html
- src/app/devices/kvm/kvm.component.ts
- src/app/devices/sol/sol.component.html
- src/app/devices/sol/sol.component.ts
removes confusing KVM and SOL buttons from persistent toolbar and moves them to respective kvm and sol pages
> refactor: address UX for KVM and SOL connection

- src/app/devices/event-log/event-log.component.ts
- src/app/devices/general/general.component.html
- src/app/devices/general/general.component.ts
- src/app/devices/hardware-information/hardware-information.component.html
- src/app/devices/hardware-information/hardware-information.component.ts
> feat: add loading indicators for hwinfo and general info

- src/app/devices/device-detail/device-detail.component.html
- src/app/devices/device-detail/device-detail.component.ts
- src/app/devices/devices.component.html
- src/app/explorer/explorer.component.spec.ts
- src/app/explorer/explorer.component.ts
> refactor: moves explorer to device detail page

- cypress/e2e/integration/device/device-details.spec.ts
- src/app/devices/devices.service.spec.ts
- src/app/devices/devices.service.ts
- src/app/devices/hardware-information/hardware-information.component.html
- src/app/devices/hardware-information/hardware-information.component.spec.ts
- src/app/devices/hardware-information/hardware-information.component.ts
- src/models/models.ts
> fix: update hardware information of device

- src/app/devices/audit-log/audit-log.component.html
- src/app/devices/audit-log/audit-log.component.ts
- src/app/devices/device-detail/device-detail.component.html
- src/app/devices/device-detail/device-detail.component.ts
- src/app/devices/devices.service.ts
- src/app/devices/event-log/event-log.component.html
- src/app/devices/event-log/event-log.component.ts
- src/app/devices/network-settings/network-settings.component.html
- src/app/devices/network-settings/network-settings.component.spec.ts
- src/app/devices/network-settings/network-settings.component.ts
> feat: display network settings

- src/app/devices/device-detail/device-detail.component.ts
> fix: menu options no longer duplicate

- src/app/devices/devices.component.html
the tooltip for bulk actions now reflects deactivate vs delete based on cloud/console mode.
closes: #2112
> fix: tooltip for bulk action

- src/app/devices/devices.component.html
> fix: remove disabled attribute from tag and instead use disableRipple

- src/app/devices/devices.component.ts
removes status column and removes power status call in console mode on devices page as this begins to cause detrimental performance with multiple devices offline (multiple API calls timing out)
closes: #2116, #2117
> fix: bulk delete is now throttled

- src/locale/messages.xlf
> style: update base translation file

- src/app/authorize.interceptor.ts
> fix: prevent if-match header if version is blank

- src/app/devices/devices.component.html
- src/app/devices/devices.component.ts
> fix: hides erroneous icon for deletion

- src/app/explorer/explorer.component.html
- src/app/explorer/explorer.component.spec.ts
- src/app/explorer/explorer.component.ts
> fix: automatically clears explorer selection field on click

- src/app/devices/certificates/certificates.component.html
- src/app/devices/certificates/certificates.component.spec.ts
- src/app/devices/certificates/certificates.component.ts
- src/app/devices/device-detail/device-detail.component.html
- src/app/devices/device-detail/device-detail.component.ts
- src/app/devices/devices.service.ts
> feat: adds section to device info for certificate information and allows for downloading of certs

- src/app/devices/device-toolbar/device-toolbar.component.html
> fix: deactivate button tooltip

- src/app/shared/add-device-enterprise/add-device-enterprise.component.html
- src/app/shared/add-device-enterprise/add-device-enterprise.component.ts
> feat: add validation for username length

- src/app/core/navbar/navbar.component.html
- src/app/dashboard/dashboard.component.html
- src/app/dashboard/dashboard.component.scss
- src/app/dashboard/dashboard.component.ts
> feat: hide menu for console and update dashboard

- src/app/devices/general/general.component.ts
> fix: show success message on amt features update

- src/app/devices/network-settings/network-settings.component.html
> fix: handles empty values in DTO for network page

- src/app/devices/device-toolbar/device-toolbar.component.ts
- src/app/devices/kvm/kvm.component.spec.ts
- src/app/devices/kvm/kvm.component.ts
- src/app/devices/sol/sol.component.spec.ts
- src/app/devices/sol/sol.component.ts
- src/app/devices/user-consent.service.spec.ts
- src/app/devices/user-consent.service.ts
- src/models/models.ts
> fix: accept user consent code for advanced power actions

- src/app/devices/kvm/kvm.component.html
- src/app/devices/kvm/kvm.component.ts
- src/app/devices/sol/sol.component.ts
> fix: KVM/SOL disconnect on close

- src/app/devices/general/general.component.html
- src/app/devices/general/general.component.ts
> fix: resolves handling when when amt redirection features are available

- src/app/devices/general/general.component.html
- src/app/devices/general/general.component.ts
> feat: translate amt sku value to human readable string

- package-lock.json
- package.json
- src/app/devices/sol/sol.component.html
> fix: shows disconnect button on sol connection

- src/app/authorize.interceptor.ts
> feat: indicate when device does not respond

- src/app/devices/alarms/alarms.component.html
- src/app/devices/alarms/alarms.component.ts
- src/app/devices/devices.service.spec.ts
- src/app/devices/devices.service.ts
- src/models/models.ts
> fix: add and delete alarm works now

- src/app/devices/network-settings/network-settings.component.html
> fix: network settings displays only available interfaces

- src/app/auth.service.ts
- src/app/core/toolbar/toolbar.component.html
> feat: enable auth for console mode

- src/app/profiles/profile-detail/profile-detail.component.ts
> fix: profile now handles direct connection mode correctly

- package-lock.json
- package.json
@angular/cdk               18.2.8 -> 18.2.9
@angular/cli               18.2.8 -> 18.2.9
@angular/material          18.2.7 -> 18.2.9
> build(deps): bump angular to 18.2.9

- src/app/devices/device-toolbar/device-toolbar.component.html
- src/app/devices/device-toolbar/device-toolbar.component.ts
- src/app/devices/devices.component.html
- src/app/devices/devices.component.ts
fixes issue with tag editing as well
closes Show current power status on device details page #2283
> feat: add power state to device details

- src/app/devices/network-settings/network-settings.component.html
> feat: add local Profile Synchronization to wireless network

- src/app/devices/kvm/kvm.component.ts
> feat: re-enable auth for ws when in console mode

- src/app/authorize.interceptor.ts
> fix: logout user if 401 from server

- src/app/core/navbar/navbar.component.html
- src/app/core/navbar/navbar.component.ts
> fix: disables CIRA in non-cloud mode

- src/app/devices/device-toolbar/device-toolbar.component.html
- src/app/devices/device-toolbar/device-toolbar.component.ts
> fix: update power button for hard reset

- src/app/devices/audit-log/audit-log.component.html
- src/app/devices/audit-log/audit-log.component.spec.ts
- src/app/devices/audit-log/audit-log.component.ts
- src/app/devices/device-log.service.spec.ts
- src/app/devices/device-log.service.ts
- src/app/devices/devices.service.spec.ts
- src/app/devices/devices.service.ts
- src/app/devices/event-log/event-log.component.html
- src/app/devices/event-log/event-log.component.spec.ts
- src/app/devices/event-log/event-log.component.ts
> feat: enable download for audit/event logs

- angular.json
- package-lock.json
- package.json
- src/app/devices/kvm/kvm.component.html
- src/app/devices/kvm/kvm.component.scss
- src/app/devices/kvm/kvm.component.spec.ts
- src/app/devices/kvm/kvm.component.ts
- src/app/devices/sol/sol.component.spec.ts
> feat: enable KVM fullscreen mode

- angular.json
- package.json
- src/environments/environment.enterprise.dev.ts
> build: provide a dev enterprise configuration for better dx

- package-lock.json
- package.json
> build(deps): update angular

- .github/workflows/trivy-scan.yaml
> ci: upload trivy result scan

- src/app/devices/device-log.service.ts
- src/app/devices/event-log/event-log.component.html
- src/app/devices/event-log/event-log.component.scss
- src/app/devices/event-log/event-log.component.spec.ts
- src/app/devices/event-log/event-log.component.ts
- src/models/models.ts
> fix: add pagination for event logs

- src/app/devices/explorer/explorer.component.ts
- src/app/devices/user-consent.service.spec.ts
> fix: add NGX_MONACO_EDITOR_CONFIG provider to ExplorerComponent

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- cypress/e2e/integration/domain/create.spec.ts
- cypress/e2e/integration/domain/delete.spec.ts
- cypress/e2e/integration/domain/duplicate.spec.ts
- src/app/core/about/about.component.html
- src/app/core/toolbar/toolbar.component.html
- src/app/dashboard/dashboard.component.html
- src/app/login/login.component.html
- src/index.html
> refactor: rename open-amt-cloud-toolkit to device-management-toolkit

- .github/workflows/docker.yaml
- .releaserc.json
- src/app/profiles/profile-detail/profile-detail.component.spec.ts
> feat(docker): enable multiarch build

- .github/workflows/release.yml
> ci: adds buildx support

- .devcontainer/devcontainer.json
- README.md
- angular.json
- [ N/A ] Unit Tests have been added for new changes
- [ N/A ] API tests have been updated if applicable
- [ N/A ] All commented code has been removed
- [ N/A ] If you've added a dependency, you've ensured license is compatible with Apache 2.0 and clearly outlined the added dependency.
Add support for devcontainer in vscode.
Feature device-management-toolkit/cloud-deployment#383
> feat(docker): add support for devcontainer

- src/app/auth.service.ts
> fix: address an issue where login token might not exist

- src/app/devices/device-toolbar/device-toolbar.component.spec.ts
- src/app/devices/device-toolbar/device-toolbar.component.ts
- src/app/devices/general/general.component.html
> fix: add tooltip to https network boot

- src/app/devices/certificates/certificates.component.ts
- src/app/devices/device-toolbar/device-toolbar.component.ts
- src/app/devices/device-toolbar/http-boot-dialog/http-boot-dialog.component.html
- src/app/devices/device-toolbar/http-boot-dialog/http-boot-dialog.component.spec.ts
> fix: remove username and password from https boot

- src/assets/i18n/en.json
> fix: correct HTTPS boot message

- src/app/configs/config-detail/config-detail.component.ts
- src/app/domains/domain-detail/domain-detail.component.ts
- src/app/ieee8021x/ieee8021x-detail/ieee8021x-detail.component.ts
- src/app/profiles/profile-detail/profile-detail.component.ts
- src/app/wireless/wireless-detail/wireless-detail.component.ts
- src/assets/i18n/en.json
> fix: fixes wireless config name translation

- src/app/devices/device-toolbar/device-toolbar.component.html
- src/app/devices/general/general.component.html
> refactor: optimizations for data processing

- .releaserc.json
change webui to web-ui for new docker name in device-mgmt-toolkit to better align with naming conventions
> ci: change webui to web-ui for new docker name

- src/app/devices/general/general.component.html
- src/app/devices/general/general.component.ts
> feat: adds http, winre and pba support to ocr status

- src/app/devices/certificates/add-cert-dialog/add-cert-dialog.component.ts
> fix: status update on cert upload in devices

- src/app/devices/certificates/add-cert-dialog/add-cert-dialog.component.html
- src/app/domains/domain-detail/domain-detail.component.html
> fix: domain cert upload status

- src/app/devices/devices.component.spec.ts
- src/app/devices/devices.component.ts
> fix: device power status

- src/app/devices/devices.component.spec.ts
- src/app/devices/devices.service.spec.ts
- src/app/devices/devices.service.ts
- src/app/devices/kvm/kvm.component.html
- src/app/devices/kvm/kvm.component.spec.ts
- src/app/devices/kvm/kvm.component.ts
- src/models/models.ts
> feat: enable selecting display
